config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'static_pages#home'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    resources :invitations
  end

  resources :events do
    resources :invitations
  end

  resources :invitations do
    delete :reject, on: :member
    delete :accept, on: :member
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User"
  has_many :rsvps, foreign_key: "attended_event_id"
  has_many :attendees, :through => :rsvps
  has_many :invitations, foreign_key: "invited_event_id"
  has_many :invitees, :through => :invitations

  scope :past, -> { where('date < ?', Time.now) }
  scope :upcoming, -> { where('date > ?', Time.now) }



end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :invitee, class_name: 'User'
  belongs_to :invited_event, class_name: 'Event'




end

app/models/rsvp.rb
class Rsvp < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :hosted_events, class_name: "Event", dependent: :destroy, foreign_key: "creator_id"
  has_many :rsvps, foreign_key: "attendee_id"
  has_many :attended_events, :through => :rsvps
  has_many :invitations, foreign_key: "invitee"
  has_many :invited_events, :through => :invitations


  def upcoming_events
    self.attended_events.where('date > ?', Time.now)
  end

  def previous_events
    self.attended_events.where('date < ?', Time.now)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController


  def index
    @past_events = Event.past
    @upcoming_events = Event.upcoming
  end

  def new
    @event = current_user.hosted_events.build
  end

  def show
    @event = Event.find(params[:id])
    @attendees = @event.attendees
    @invitees = @event.invitees
  end

  def create
    @user = current_user
    @event = @user.hosted_events.build(event_params)
    if @event.save
      redirect_to @user
    else
      render 'new'
    end
  end


private ###########################################################

def event_params
  params.require(:event).permit(:title, :details, :date)
end

end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_action :correct_user, only: [:reject, :accept]

  def show
    @invitation = Invitation.find(params[:id])
  end


  def reject
    @invitation.destroy
    redirect_to current_user
  end

  def accept
    @rsvp = Rsvp.new(attendee_id: @invitation.invitee_id, attended_event_id: @invitation.invited_event_id)
    if @rsvp.save
      @invitation.destroy
      redirect_to @rsvp.attended_event
    else
      render 'invitation'
    end
  end


  def new
    @event = Event.find(params[:event_id])
    @invitation = @event.invitations.build

  end

  def create
    @event = Event.find(params[:event_id])
    @invitation = @event.invitations.build(invitation_params)
    if @invitation.save
      redirect_to @event
    else
      render 'new'
    end

  end

private ########################################333

  def invitation_params
    params.require(:invitation).permit(:message, :invitee_id, :date)
  end

  def correct_user
    @invitation = current_user.invitations.find_by(id: params[:id])
    redirect_to root_url if @invitation.nil?
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


  def new
  end

  def create
    @user = User.find_by_username(params[:session][:username])
    if @user
      log_in(@user)
      redirect_to @user
    else
      flash[:danger] = "No such username"
      redirect_to root_path
    end
  end

  def destroy
    log_out 
    redirect_to root_path
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    @users = User.all
    @events = Event.all 
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to Private Event thanks for signing up!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @hosted_events = @user.hosted_events.all
    @upcoming_events = @user.upcoming_events
    @previous_events = @user.previous_events
    @invitations = @user.invitations.all
  end

  def index
  end

  private ###########################################################

  def user_params
    params.require(:user).permit(:username)
  end

  


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper

  def current_user_owns_event?(event)
    if event.creator == current_user
      true
    else
      false
    end
  end
end

app/helpers/invitations_helper.rb
module InvitationsHelper


  def current_user_invited_to_event?(event)
    if event.invitees.any? {|invitee| invitee == current_user }
      true
    else
      false
    end
  end


end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end 

  def current_user
    @current_user ||=  User.find_by_id(session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<br>
<br>
<h3> past_events </h3>
<% @past_events.each do |event| %>
  <ul>
    <li>Title: <%= event.title %> </li>
    <li>Creator: <%= event.creator.username %></li>
    <li>Details: <%= event.details %> </li>
    <li>Time: <%= event.date %> </li>
  </ul>
  <br>
<% end %>

<br>
<br>
<h3> upcoming_events </h3>
<% @upcoming_events.each do |event| %>
  <ul>
    <li>Title: <%= event.title %> </li>
    <li>Creator: <%= event.creator.username %></li>
    <li>Details: <%= event.details %> </li>
    <li>Time: <%= event.date %> </li>
  </ul>
  <br>
<% end %>

app/views/events/new.html.erb
<h3> Make a new Event! </h3>
<% if logged_in? %>
  <p> Current Logged In User: <%= current_user.username %> </p>
<% end %>
<br>
<br>
<%= form_for @event do |f| %>
  <%= f.label :title%>
  <%= f.text_field :title %>
  <br>
  <br>
  <%= f.label :details%>
  <%= f.text_field :details %>
  <br>
  <br>
  <%= f.label :date%>
  <%= f.date_select :date %>
  <br>
  <br>
  <%= f.submit %>
<% end %>

app/views/events/show.html.erb
<%= link_to "home", root_path %>
<% if logged_in? %>
  <p> Current Logged In User: <%= current_user.username %> </p>
<% end %>
<ul>
  <li>Title: <%= @event.title %> </li>
  <li>Host: <%= @event.creator.username %> </li>
  <li>Details: <%= @event.details %> </li>
  <li>Time: <%= @event.date %> </li>
</ul>

<% if current_user_owns_event?(@event) %>
 <%= link_to "Invite someone to this event", new_event_invitation_path(@event) %>
<% end %>

<% if current_user_invited_to_event?(@event) %>
  <h3> You have been invited to this event! </h3>
  <%= link_to "Review Invitation", user_invitation_path(@event) %>
<% end %>


<h3> Here are the people coming: </h3>
<ul>
  <% @attendees.each do |attendee| %>
    <li><%= link_to attendee.username, attendee %></li>
  <% end %>
</ul>

<h3> Here are the people invited: </h3>
<ul>
  <% @invitees.each do |invitee| %>
    <li><%= link_to invitee.username, invitee %></li>
  <% end %>

</ul>

app/views/invitations/new.html.erb
<h3> New Invitation for <%= @event.title %>
<br>
<br>
<%= form_for ([@event, @invitation]) do |f| %>
  <%= f.label :message %>
  <%= f.text_field :message %>
  <br>
  <br>
  <%= f.label :username %>
  <%= f.collection_select :invitee_id, User.order(:username), :id, :username %>
  <br>
  <br>
  <%= f.submit "Submit" %>
<% end %>

app/views/invitations/show.html.erb
<h3> This is an invitation for
<%= @invitation.invited_event.title %> </h3>
<p> To: <%= @invitation.invitee.username %>  </p>
<p> From: <%= @invitation.invited_event.creator.username %> sent it to you! </p>
<p> Message: <%= @invitation.message %> </p>

<%= link_to "Accept", accept_invitation_path, :method => :delete %>
<%= link_to "Reject", reject_invitation_path, :method => :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<h1>Welcome to Private Event</h1>
<br>
<br>
<% if logged_in? %>
  <p> A user is logged in </p>
<% else %>
  <p> No logged in user </p>
<% end %>
<br>
<h3>Currently logged in user here: </h3>
<% if logged_in? %>
  <%= current_user.username %>
<% end %>
<br>
<br>
<% if logged_in? %>
  <%= link_to "Log Out", logout_path, method: "delete" %>
<% else %>
  <%= link_to "Signup Here", '/signup' %>
  <br>
  <br>
  <p> or </p>
  <br>
  <p>Please login here:</p>
  <%= form_for(:session, url: login_path) do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username %>
    <%= f.submit "log in" %>
  <% end %>
<% end %>

<br>
<h3> All Active Users </h3>
<ul>
<% @users.each do |user| %>
  <li><%= link_to "#{user.username}", user %></li>
<% end %>
</ul>
<br>
<br>
<h3> All Events </h3>
<ul>
<% @events.each do |event| %>
  <li><%= link_to "#{event.title}, #{event.date}", event %></li>
<% end %>
</ul>

app/views/users/new.html.erb
<p> Cool, please sign up! </p>

<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1> Welcome to <%= @user.username %>'s Page! </h1>
<% if logged_in? %>
  <p> Current Logged In User: <%= current_user.username %> </p>
<% end %>
<br>
<%= link_to "Home", root_path %>
<br>
<%= link_to "Host a New Event!", new_event_path %>
<br>
<h3> Here are the events the user is hosting: </h3>

<% @hosted_events.each do |event| %>
  <ul>
    <li><%= link_to "See Event", event %></li>
    <li>Title: <%= event.title %> </li>
    <li>Details: <%= event.details %> </li>
    <li>Time: <%= event.date %> </li>
  </ul>
<% end %>

<br>
<br>
<h3> Here are the previously attended events: </h3>
<% @previous_events.each do |event| %>
  <ul>
    <li><%= link_to "See Event", event %></li>
    <li>Title: <%= event.title %> </li>
    <li>Host: <%= event.creator.username %> </li>
    <li>Details: <%= event.details %> </li>
    <li>Time: <%= event.date %> </li>
  </ul>
<% end %>

<br>
<br>
<h3> Here are the upcoming events: </h3>
<% @upcoming_events.each do |event| %>
  <ul>
    <li><%= link_to "See Event", event %></li>
    <li>Title: <%= event.title %> </li>
    <li>Host: <%= event.creator.username %> </li>
    <li>Details: <%= event.details %> </li>
    <li>Time: <%= event.date %> </li>
  </ul>
<% end %>

<br>
<br>
<% if current_user == @user %>
  <h3> Here are the events the user is invited to: (<%= @user.invitations.count %>)</h3>
  <% @invitations.each do |invitation| %>
    <ul>
      <li><%= link_to "See Invitation", invitation %></li>
      <li>Title: <%= invitation.invited_event.title %> </li>
      <li>Host: <%= invitation.invited_event.creator.username %> </li>
      <li>Details: <%= invitation.invited_event.details %> </li>
      <li>Time: <%= invitation.invited_event.date %> </li>

    </ul>

  <% end %>
<% end %>